# Generated by Django 6.0 on 2026-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Client Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='entity_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('partnership', 'Partnership'), ('other', 'Other')], default='company', max_length=20, verbose_name='Entity Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Friendly Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
